# Generated by Django 2.2.6 on 2021-03-15 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_auto_20210315_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_data',
            old_name='id_no',
            new_name='clg_id_no',
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 15, 22, 13, 49, 641776)),
        ),
    ]
