# Generated by Django 2.2.6 on 2021-03-17 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_auto_20210317_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='depart_name',
            new_name='faculty_name',
        ),
        migrations.RemoveField(
            model_name='events',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='events',
            name='facultyy_name',
        ),
        migrations.AddField(
            model_name='events',
            name='file',
            field=models.FileField(blank=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='events',
            name='instructions',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='events',
            name='url',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 17, 21, 31, 57, 201347)),
        ),
    ]
