# Generated by Django 2.2.6 on 2021-03-17 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_auto_20210317_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='faculty_name',
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 17, 21, 57, 56, 990238)),
        ),
    ]
