# Generated by Django 3.1.5 on 2021-03-17 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_auto_20210317_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 17, 23, 48, 21, 799418)),
        ),
    ]
