# Generated by Django 2.2.6 on 2021-03-16 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_auto_20210315_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='achieve_id',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='field_type',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='rating_star',
        ),
        migrations.RemoveField(
            model_name='project',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='certificate_img',
            field=models.FileField(null=True, upload_to='achievements/'),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 16, 13, 40, 34, 81369)),
        ),
    ]
