# Generated by Django 2.2.6 on 2021-03-18 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0004_auto_20210317_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('first_year', models.IntegerField(blank=True)),
                ('second_year', models.IntegerField(blank=True)),
                ('third_year', models.IntegerField(blank=True)),
                ('fourth_year', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 18, 11, 47, 23, 425225)),
        ),
    ]
