# Generated by Django 3.1.5 on 2021-03-18 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0004_auto_20210317_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 18, 14, 27, 8, 428789)),
        ),
    ]
