# Generated by Django 3.1.5 on 2021-03-18 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0005_auto_20210318_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='a_skills',
        ),
        migrations.AddField(
            model_name='skills',
            name='skill',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 18, 18, 39, 45, 6327)),
        ),
        migrations.RemoveField(
            model_name='student',
            name='skills',
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.ManyToManyField(related_name='students_skills', to='campus.Skills'),
        ),
    ]
