# Generated by Django 2.2.6 on 2021-03-18 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0006_auto_20210318_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='id_no',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 18, 12, 8, 30, 880345)),
        ),
    ]
