# Generated by Django 2.2.6 on 2021-03-18 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0008_auto_20210318_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 18, 14, 9, 2, 539502)),
        ),
        migrations.AlterField(
            model_name='marks',
            name='first_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='marks',
            name='fourth_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='marks',
            name='second_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='marks',
            name='third_year',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
