# Generated by Django 3.1.5 on 2021-03-18 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0008_auto_20210318_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 18, 18, 46, 59, 720286)),
        ),
    ]
