# Generated by Django 3.1.5 on 2021-03-18 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0011_auto_20210318_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 18, 20, 31, 58, 93034)),
        ),
        migrations.AlterField(
            model_name='student',
            name='Id_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
