# Generated by Django 3.1.5 on 2021-03-18 18:16

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0012_auto_20210318_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 18, 23, 46, 14, 339688)),
        ),
        migrations.AlterField(
            model_name='student',
            name='Id_number',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='dept',
            field=models.CharField(blank=True, choices=[('Mechanical', 'Mechanical'), ('EC', 'EC'), ('Civil', 'Civil'), ('IT', 'IT'), ('EL', 'EL'), ('EE', 'EE'), ('Production', 'Production')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='fname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='hsc',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_no',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='interest',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('wd', 'Web Development'), ('ad', 'App Development'), ('cd', 'Cloud Computing'), ('excel', 'Excel'), ('wp', 'Wordpress'), ('react', 'React'), ('dj', 'Django'), ('bc', 'Block Chain'), ('dm', 'Data Mining'), ('py', 'Python'), ('c', 'C/C++'), ('j', 'Java')], default='', max_length=39),
        ),
        migrations.AlterField(
            model_name='student',
            name='lname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='permanent_address',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='student',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='resident_address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='ssc',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
