# Generated by Django 3.1.5 on 2021-03-19 03:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0014_auto_20210319_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 19, 8, 56, 11, 158824)),
        ),
        migrations.AlterField(
            model_name='student',
            name='hsc_result',
            field=models.FileField(blank=True, default='', upload_to='hsc_results/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ssc_result',
            field=models.FileField(blank=True, default='', upload_to='ssc_results/'),
        ),
    ]
